name: Build & Deploy to Cloud Run
'on':
  push:
    branches:
      - main

env:
  DATABASE_URL: ${{ secrets.SQL_PROXY_DATABASE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag ${{ secrets.IMAGE_TAG }} \
              --gcs-log-dir gs://travellabel_cloudbuild_logs

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} \
              --image ${{ secrets.IMAGE_TAG }} \
              --region asia-southeast2

      - name: Download Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

      - name: Initialize and Migrate via Cloud SQL Proxy connection
        run: |
          ./cloud_sql_proxy -instances=${{ secrets.GCP_SQL_CONNECTION_NAME }}=tcp:5432 & npx prisma migrate deploy
